<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.coremedia.plugins</groupId>
  <artifactId>studio-server.coremedia-workflow-management-plugin</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>coremedia-plugin</packaging>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <cm.studio-server.core.version>2404.1</cm.studio-server.core.version>
    <cm.common.core.version>2404.1</cm.common.core.version>
    <cm.middle.core.version>2404.1</cm.middle.core.version>
    <maven-dependency-plugin.version>3.8.1</maven-dependency-plugin.version>
    <exec-maven-plugin.version>3.5.0</exec-maven-plugin.version>
    <maven-install-plugin.version>3.1.3</maven-install-plugin.version>
    <maven-javadoc-plugin.version>3.11.1</maven-javadoc-plugin.version>
    <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
    <maven-deploy-plugin.version>3.1.3</maven-deploy-plugin.version>
    <spring-boot-restclient.version>4.0.0</spring-boot-restclient.version>
  </properties>

  <repositories>
    <repository>
      <id>coremedia.external.releases</id>
      <url>https://repository.coremedia.com/nexus/content/groups/cms/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>coremedia.external.releases</id>
      <url>https://repository.coremedia.com/nexus/content/groups/cms/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.coremedia.cms</groupId>
        <artifactId>studio-server-core-bom</artifactId>
        <version>${cm.studio-server.core.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.coremedia.cms</groupId>
        <artifactId>studio-server-thirdparty-for-plugins-bom</artifactId>
        <version>${cm.studio-server.core.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.coremedia.cms</groupId>
        <artifactId>common-core-bom</artifactId>
        <version>${cm.common.core.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.coremedia.cms</groupId>
        <artifactId>middle-core-bom</artifactId>
        <version>${cm.middle.core.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.coremedia.cms</groupId>
      <artifactId>common.beans-for-plugins-container</artifactId>
      <scope>provided</scope>
    </dependency>

    <!--dependency>
      <groupId>com.coremedia.cms</groupId>
      <artifactId>common.plugin-base</artifactId>
      <scope>provided</scope>
    </dependency-->

    <!--dependency>
      <groupId>com.coremedia.cms</groupId>
      <artifactId>coremedia-common</artifactId>
      <scope>provided</scope>
    </dependency-->
    <!--dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>provided</scope>
    </dependency-->
    <dependency>
      <groupId>com.coremedia.cms</groupId>
      <artifactId>cap-unified-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <scope>provided</scope>
    </dependency>
    <!--dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <scope>provided</scope>
    </dependency-->
    <!--dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot</artifactId>
      <scope>provided</scope>
    </dependency-->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-autoconfigure</artifactId>
      <scope>provided</scope>
    </dependency>
    <!--dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <scope>provided</scope>
    </dependency-->
    <!--dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
      <scope>provided</scope>
    </dependency-->

    <!--dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>3.12.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.24.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>3.12.4</version>
      <scope>test</scope>
    </dependency-->
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <configuration>
          <ignoredDependencies>
            <!-- JUnit Jupiter: Use Aggregator rather than API/Engine Artifacts directly -->
            <ignoredDependency>org.junit.jupiter:junit-jupiter</ignoredDependency>
            <ignoredDependency>org.junit.jupiter:junit-jupiter-api</ignoredDependency>
            <ignoredDependency>org.junit.jupiter:junit-jupiter-params</ignoredDependency>
          </ignoredDependencies>
          <ignoreUnusedRuntime>true</ignoreUnusedRuntime>
        </configuration>
        <executions>
          <execution>
            <id>analyze-duplicate</id>
            <goals>
              <goal>analyze-duplicate</goal>
            </goals>
          </execution>
          <execution>
            <id>analyze-only</id>
            <goals>
              <goal>analyze-only</goal>
            </goals>
            <configuration>
              <failOnWarning>true</failOnWarning>
              <ignoreNonCompile>false</ignoreNonCompile>
              <ignoredUnusedDeclaredDependencies>
                <ignoredUnusedDeclaredDependency>*:*-javadoc</ignoredUnusedDeclaredDependency>
              </ignoredUnusedDeclaredDependencies>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.coremedia.maven</groupId>
        <artifactId>coremedia-plugins-maven-plugin</artifactId>
        <version>4.0.2</version>
        <extensions>true</extensions>
        <configuration>
          <pluginId>${project.artifactId}</pluginId>
          <zip>true</zip>
          <pluginConfigurationClass>com.coremedia.cms.plugins.studio_tracking.PluginConfiguration</pluginConfigurationClass>
          <pluginProvider>CoreMedia</pluginProvider>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>${maven-deploy-plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>${maven-install-plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${maven-javadoc-plugin.version}</version>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <!--profile>
      <id>find-api-violations</id>
      <dependencies>
        <dependency>
          <groupId>com.coremedia.blueprint.base</groupId>
          <artifactId>common-javadoc</artifactId>
          <version>${cm.studio-server.core.version}</version>
          <classifier>javadoc</classifier>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>com.coremedia.blueprint.base</groupId>
          <artifactId>common-internal-javadoc</artifactId>
          <version>${cm.studio-server.core.version}</version>
          <classifier>javadoc</classifier>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>com.coremedia.blueprint.base</groupId>
          <artifactId>middle-javadoc</artifactId>
          <version>${cm.studio-server.core.version}</version>
          <classifier>javadoc</classifier>
          <scope>test</scope>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>unpack-javadoc-dependencies</id>
                <goals>
                  <goal>unpack-dependencies</goal>
                </goals>
                <phase>generate-resources</phase>
                <configuration>
                  <includeScope>test</includeScope>
                  <includeClassifiers>javadoc</includeClassifiers>
                  <classifier>javadoc</classifier>
                  <stripVersion>true</stripVersion>
                  <includes>package-list,internal-package-list</includes>
                  <useSubDirectoryPerArtifact>true</useSubDirectoryPerArtifact>
                  <outputDirectory>${project.build.directory}/javadoc-dependencies</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>${exec-maven-plugin.version}</version>
            <executions>
              <execution>
                <id>find-api-violations</id>
                <phase>verify</phase>
                <goals>
                  <goal>exec</goal>
                </goals>
                <configuration>
                  <executable>${project.basedir}/find-api-violations.sh</executable>
                  <arguments>
                    <argument>${project.basedir}</argument>
                    <argument>${project.build.directory}/javadoc-dependencies</argument>
                  </arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile-->
  </profiles>
</project>
